version: '3.5'

services:
  etl:
    image: harbor.athenafederation.org/etl-chul-mm/etl:image_tag
    volumes:
      - "./log:/log"
      - "data_folder:/data"
    networks:
      - athena_feder8-net
    environment:
      DB_DBMS: "postgresql"
      DB_SERVER : "postgres"
      DB_PORT: "5432"
      DB_DBNAME: "OHDSI"
      DB_SCHEMA: "omopcdm"
      DB_USER: db_username
      DB_PASSWORD: db_password
      VERBOSITY_LEVEL: verbosity_level
      DATE_LAST_EXPORT: date_last_export

networks:
  athena_feder8-net:
      name: feder8-net
      external: true
